// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: alarm_state.sql

package storage

import (
	"context"
)

const acknowledgeAlarmState = `-- name: AcknowledgeAlarmState :exec
UPDATE alarm_state SET acked_at = ? WHERE id = ?
`

type AcknowledgeAlarmStateParams struct {
	AckedAt *string
	ID      int64
}

func (q *Queries) AcknowledgeAlarmState(ctx context.Context, arg AcknowledgeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, acknowledgeAlarmState, arg.AckedAt, arg.ID)
	return err
}

const completeAlarmDispatch = `-- name: CompleteAlarmDispatch :execrows
UPDATE alarm_state
SET dispatch_status = 'delivered',
    claim_token = NULL,
    delivered_at = ?1,
    retry_at = NULL,
    last_error = NULL
WHERE id = ?2
  AND claim_token = ?3
  AND dispatch_status = 'dispatching'
`

type CompleteAlarmDispatchParams struct {
	DeliveredAt *string
	ID          int64
	ClaimToken  *string
}

// Finish a dispatch. Only the claim token owner may complete the row, so a
// stale process that lost its lease cannot overwrite a newer attempt.
// RowsAffected == 0 means the ownership was lost. The notification may
// already be sent. The caller must not write the row again.
func (q *Queries) CompleteAlarmDispatch(ctx context.Context, arg CompleteAlarmDispatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, completeAlarmDispatch, arg.DeliveredAt, arg.ID, arg.ClaimToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const createAlarmState = `-- name: CreateAlarmState :one
INSERT INTO alarm_state (
    alarm_id, event_id, trigger_at, fired_at,
    dispatch_status, claimed_at, claim_token, attempts
)
SELECT ?1, ?2, ?3, ?4,
       'dispatching', ?5, ?6, 1
WHERE EXISTS (
    SELECT 1 FROM event_alarms
    WHERE id = ?1 AND action IN ('AUDIO','DISPLAY','EMAIL')
)
RETURNING id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to, dispatch_status, claimed_at, claim_token, attempts, retry_at, last_error, delivered_at
`

type CreateAlarmStateParams struct {
	AlarmID    int64
	EventID    int64
	TriggerAt  string
	FiredAt    *string
	ClaimedAt  *string
	ClaimToken *string
}

// Claim a fire slot for one alarm. The EXISTS arm reads the action in the
// same statement as the insert, so a sync pull that rewrites the alarm to
// a sync-only action between the check and the claim cannot leave a fired
// state for an alarm the user disabled (issue #579). Zero rows means the
// claim failed, and the caller reports sql.ErrNoRows.
// The row enters in the "dispatching" state. It reaches "delivered" only
// through CompleteAlarmDispatch. A failed dispatch moves to "retry", and a
// process death leaves a stale "dispatching" row the next checker takes
// over via TakeoverAlarmDispatch.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) CreateAlarmState(ctx context.Context, arg CreateAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, createAlarmState,
		arg.AlarmID,
		arg.EventID,
		arg.TriggerAt,
		arg.FiredAt,
		arg.ClaimedAt,
		arg.ClaimToken,
	)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
		&i.DispatchStatus,
		&i.ClaimedAt,
		&i.ClaimToken,
		&i.Attempts,
		&i.RetryAt,
		&i.LastError,
		&i.DeliveredAt,
	)
	return i, err
}

const deleteAlarmStatesByEventID = `-- name: DeleteAlarmStatesByEventID :exec
DELETE FROM alarm_state WHERE event_id = ?
`

func (q *Queries) DeleteAlarmStatesByEventID(ctx context.Context, eventID int64) error {
	_, err := q.db.ExecContext(ctx, deleteAlarmStatesByEventID, eventID)
	return err
}

const getAlarmState = `-- name: GetAlarmState :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to, dispatch_status, claimed_at, claim_token, attempts, retry_at, last_error, delivered_at FROM alarm_state WHERE alarm_id = ? AND trigger_at = ?
`

type GetAlarmStateParams struct {
	AlarmID   int64
	TriggerAt string
}

func (q *Queries) GetAlarmState(ctx context.Context, arg GetAlarmStateParams) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmState, arg.AlarmID, arg.TriggerAt)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
		&i.DispatchStatus,
		&i.ClaimedAt,
		&i.ClaimToken,
		&i.Attempts,
		&i.RetryAt,
		&i.LastError,
		&i.DeliveredAt,
	)
	return i, err
}

const getAlarmStateByID = `-- name: GetAlarmStateByID :one
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to, dispatch_status, claimed_at, claim_token, attempts, retry_at, last_error, delivered_at FROM alarm_state WHERE id = ?
`

func (q *Queries) GetAlarmStateByID(ctx context.Context, id int64) (AlarmState, error) {
	row := q.db.QueryRowContext(ctx, getAlarmStateByID, id)
	var i AlarmState
	err := row.Scan(
		&i.ID,
		&i.AlarmID,
		&i.EventID,
		&i.TriggerAt,
		&i.FiredAt,
		&i.AckedAt,
		&i.SnoozedTo,
		&i.DispatchStatus,
		&i.ClaimedAt,
		&i.ClaimToken,
		&i.Attempts,
		&i.RetryAt,
		&i.LastError,
		&i.DeliveredAt,
	)
	return i, err
}

const listAlarmStatesByEventID = `-- name: ListAlarmStatesByEventID :many
SELECT id, alarm_id, event_id, trigger_at, fired_at, acked_at, snoozed_to, dispatch_status, claimed_at, claim_token, attempts, retry_at, last_error, delivered_at FROM alarm_state WHERE event_id = ? ORDER BY trigger_at
`

func (q *Queries) ListAlarmStatesByEventID(ctx context.Context, eventID int64) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listAlarmStatesByEventID, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
			&i.DispatchStatus,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.Attempts,
			&i.RetryAt,
			&i.LastError,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredSnoozedAlarmStates = `-- name: ListExpiredSnoozedAlarmStates :many
SELECT s.id, s.alarm_id, s.event_id, s.trigger_at, s.fired_at, s.acked_at, s.snoozed_to, s.dispatch_status, s.claimed_at, s.claim_token, s.attempts, s.retry_at, s.last_error, s.delivered_at FROM alarm_state s
JOIN event_alarms a ON a.id = s.alarm_id
WHERE s.fired_at IS NOT NULL
  AND s.acked_at IS NULL
  AND s.snoozed_to IS NOT NULL
  AND s.snoozed_to <= ?
  AND a.action IN ('AUDIO','DISPLAY','EMAIL')
ORDER BY s.snoozed_to
`

// The same sync-only filter as ListPendingAlarmStates, for the re-fire path.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) ListExpiredSnoozedAlarmStates(ctx context.Context, snoozedTo *string) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listExpiredSnoozedAlarmStates, snoozedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
			&i.DispatchStatus,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.Attempts,
			&i.RetryAt,
			&i.LastError,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAlarmStates = `-- name: ListPendingAlarmStates :many
SELECT s.id, s.alarm_id, s.event_id, s.trigger_at, s.fired_at, s.acked_at, s.snoozed_to, s.dispatch_status, s.claimed_at, s.claim_token, s.attempts, s.retry_at, s.last_error, s.delivered_at FROM alarm_state s
JOIN event_alarms a ON a.id = s.alarm_id
WHERE s.acked_at IS NULL AND s.fired_at IS NOT NULL
  AND a.action IN ('AUDIO','DISPLAY','EMAIL')
ORDER BY s.trigger_at
`

// Hide the state of an alarm a sync pull rewrote to a sync-only action.
// The filter reads the current action, so the row comes back when a later
// pull restores a fireable action (issue #579). A retirement that wrote
// acked_at instead would consume the snooze of the user for good.
// Keep the action list in lockstep with model.FireableAlarmAction.
func (q *Queries) ListPendingAlarmStates(ctx context.Context) ([]AlarmState, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAlarmStates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AlarmState
	for rows.Next() {
		var i AlarmState
		if err := rows.Scan(
			&i.ID,
			&i.AlarmID,
			&i.EventID,
			&i.TriggerAt,
			&i.FiredAt,
			&i.AckedAt,
			&i.SnoozedTo,
			&i.DispatchStatus,
			&i.ClaimedAt,
			&i.ClaimToken,
			&i.Attempts,
			&i.RetryAt,
			&i.LastError,
			&i.DeliveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAcknowledgedAlarmStates = `-- name: PurgeAcknowledgedAlarmStates :execrows
DELETE FROM alarm_state WHERE acked_at IS NOT NULL AND trigger_at < ?
`

func (q *Queries) PurgeAcknowledgedAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeAcknowledgedAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeStaleUnacknowledgedAlarmStates = `-- name: PurgeStaleUnacknowledgedAlarmStates :execrows
DELETE FROM alarm_state
WHERE acked_at IS NULL
  AND trigger_at < ?
  AND (snoozed_to IS NULL OR snoozed_to < trigger_at)
`

func (q *Queries) PurgeStaleUnacknowledgedAlarmStates(ctx context.Context, triggerAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeStaleUnacknowledgedAlarmStates, triggerAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const refireAlarmState = `-- name: RefireAlarmState :execrows
UPDATE alarm_state
SET fired_at = ?1,
    snoozed_to = NULL,
    dispatch_status = 'dispatching',
    claimed_at = ?2,
    claim_token = ?3,
    attempts = 1,
    retry_at = NULL,
    last_error = NULL,
    delivered_at = NULL
WHERE id = ?4 AND snoozed_to IS NOT NULL
`

type RefireAlarmStateParams struct {
	FiredAt    *string
	ClaimedAt  *string
	ClaimToken *string
	ID         int64
}

// Re-fire an expired snooze and start a new dispatch cycle. The UPDATE is
// gated on snoozed_to IS NOT NULL, so it acts as an atomic claim between
// overlapping checkers. The reset fields match a fresh claim: the cycle
// starts at attempt 1 in "dispatching", with no retry or delivery record.
func (q *Queries) RefireAlarmState(ctx context.Context, arg RefireAlarmStateParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, refireAlarmState,
		arg.FiredAt,
		arg.ClaimedAt,
		arg.ClaimToken,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const retryAlarmDispatch = `-- name: RetryAlarmDispatch :execrows
UPDATE alarm_state
SET dispatch_status = 'retry',
    claim_token = NULL,
    retry_at = ?1,
    last_error = ?2
WHERE id = ?3
  AND claim_token = ?4
  AND dispatch_status = 'dispatching'
`

type RetryAlarmDispatchParams struct {
	RetryAt    *string
	LastError  *string
	ID         int64
	ClaimToken *string
}

// Release a failed dispatch for a later retry. The same token gate as
// CompleteAlarmDispatch applies. retry_at carries the deterministic
// backoff; last_error records the cause for "alarm list".
func (q *Queries) RetryAlarmDispatch(ctx context.Context, arg RetryAlarmDispatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, retryAlarmDispatch,
		arg.RetryAt,
		arg.LastError,
		arg.ID,
		arg.ClaimToken,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const snoozeAlarmState = `-- name: SnoozeAlarmState :exec
UPDATE alarm_state SET snoozed_to = ? WHERE id = ?
`

type SnoozeAlarmStateParams struct {
	SnoozedTo *string
	ID        int64
}

func (q *Queries) SnoozeAlarmState(ctx context.Context, arg SnoozeAlarmStateParams) error {
	_, err := q.db.ExecContext(ctx, snoozeAlarmState, arg.SnoozedTo, arg.ID)
	return err
}

const takeoverAlarmDispatch = `-- name: TakeoverAlarmDispatch :execrows
UPDATE alarm_state
SET dispatch_status = 'dispatching',
    claimed_at = ?1,
    claim_token = ?2,
    attempts = attempts + 1,
    fired_at = ?3,
    retry_at = NULL
WHERE id = ?4
  AND acked_at IS NULL
  AND snoozed_to IS NULL
  AND (claim_token IS NULL OR claim_token <> ?2)
  AND (
        (dispatch_status = 'retry' AND retry_at IS NOT NULL AND retry_at <= ?5)
     OR (dispatch_status = 'dispatching' AND (claimed_at IS NULL OR claimed_at <= ?6))
  )
`

type TakeoverAlarmDispatchParams struct {
	ClaimedAt     *string
	ClaimToken    *string
	FiredAt       *string
	ID            int64
	Now           *string
	LeaseBoundary *string
}

// Take over a dispatch that another checker did not finish. The row is
// eligible when it waits for a retry that is due, or when its dispatch
// lease expired (the owner process died or hung). A live claim that is
// inside its lease is not touched. Neither is a snoozed or an acknowledged
// row. The predicate on claim_token keeps a caller from taking over its
// own claim. RowsAffected == 0 means this caller lost the race or the row
// is not due. The caller then dispatches nothing.
func (q *Queries) TakeoverAlarmDispatch(ctx context.Context, arg TakeoverAlarmDispatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, takeoverAlarmDispatch,
		arg.ClaimedAt,
		arg.ClaimToken,
		arg.FiredAt,
		arg.ID,
		arg.Now,
		arg.LeaseBoundary,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
