// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_truncate_deletes.sql

package storage

import (
	"context"
)

const deleteEventTruncateDelete = `-- name: DeleteEventTruncateDelete :exec
DELETE FROM event_truncate_deletes WHERE id = ?
`

func (q *Queries) DeleteEventTruncateDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventTruncateDelete, id)
	return err
}

const deleteEventTruncateDeleteChecked = `-- name: DeleteEventTruncateDeleteChecked :execrows
DELETE FROM event_truncate_deletes WHERE id = ?
`

// Same delete as DeleteEventTruncateDelete, but it reports the number of rows
// removed. A batch apply then fails when another operation consumed the log
// row between the batch check and the batch apply.
func (q *Queries) DeleteEventTruncateDeleteChecked(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventTruncateDeleteChecked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEventTruncateDelete = `-- name: GetEventTruncateDelete :one
SELECT id, calendar_id, uid, cutoff_time, previous_rrule, deleted_at, hidden_overrides, removed_rdates FROM event_truncate_deletes WHERE id = ?
`

func (q *Queries) GetEventTruncateDelete(ctx context.Context, id int64) (EventTruncateDelete, error) {
	row := q.db.QueryRowContext(ctx, getEventTruncateDelete, id)
	var i EventTruncateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.CutoffTime,
		&i.PreviousRrule,
		&i.DeletedAt,
		&i.HiddenOverrides,
		&i.RemovedRdates,
	)
	return i, err
}

const getEventTruncateDeleteByUIDAndCutoff = `-- name: GetEventTruncateDeleteByUIDAndCutoff :one
SELECT id, calendar_id, uid, cutoff_time, previous_rrule, deleted_at, hidden_overrides, removed_rdates FROM event_truncate_deletes WHERE uid = ? AND cutoff_time = ?
`

type GetEventTruncateDeleteByUIDAndCutoffParams struct {
	Uid        string
	CutoffTime string
}

// Looks up the truncation log row by its unique (uid, cutoff_time) key so the
// TUI undo path can reverse a "this and following" delete through the same
// provenance-aware reversal the trash view uses.
func (q *Queries) GetEventTruncateDeleteByUIDAndCutoff(ctx context.Context, arg GetEventTruncateDeleteByUIDAndCutoffParams) (EventTruncateDelete, error) {
	row := q.db.QueryRowContext(ctx, getEventTruncateDeleteByUIDAndCutoff, arg.Uid, arg.CutoffTime)
	var i EventTruncateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.CutoffTime,
		&i.PreviousRrule,
		&i.DeletedAt,
		&i.HiddenOverrides,
		&i.RemovedRdates,
	)
	return i, err
}

const listEventTruncateDeletesByCalendar = `-- name: ListEventTruncateDeletesByCalendar :many
SELECT id, calendar_id, uid, cutoff_time, previous_rrule, deleted_at, hidden_overrides, removed_rdates FROM event_truncate_deletes
WHERE calendar_id = ?
ORDER BY deleted_at DESC
`

func (q *Queries) ListEventTruncateDeletesByCalendar(ctx context.Context, calendarID int64) ([]EventTruncateDelete, error) {
	rows, err := q.db.QueryContext(ctx, listEventTruncateDeletesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventTruncateDelete
	for rows.Next() {
		var i EventTruncateDelete
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.CutoffTime,
			&i.PreviousRrule,
			&i.DeletedAt,
			&i.HiddenOverrides,
			&i.RemovedRdates,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldEventTruncateDeletes = `-- name: PurgeOldEventTruncateDeletes :execrows
DELETE FROM event_truncate_deletes WHERE deleted_at < ?
`

func (q *Queries) PurgeOldEventTruncateDeletes(ctx context.Context, deletedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldEventTruncateDeletes, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordEventTruncateDelete = `-- name: RecordEventTruncateDelete :exec
INSERT INTO event_truncate_deletes (calendar_id, uid, cutoff_time, previous_rrule, hidden_overrides, removed_rdates)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(uid, cutoff_time) DO UPDATE SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type RecordEventTruncateDeleteParams struct {
	CalendarID      int64
	Uid             string
	CutoffTime      string
	PreviousRrule   string
	HiddenOverrides *string
	RemovedRdates   *string
}

// Idempotent: truncating the same cutoff twice keeps one log row. Stores
// only the FIRST previous_rrule, hidden_overrides, and removed_rdates seen so
// re-truncating doesn't overwrite the original pre-truncation state with an
// already-truncated rule or an empty override/rdate set.
func (q *Queries) RecordEventTruncateDelete(ctx context.Context, arg RecordEventTruncateDeleteParams) error {
	_, err := q.db.ExecContext(ctx, recordEventTruncateDelete,
		arg.CalendarID,
		arg.Uid,
		arg.CutoffTime,
		arg.PreviousRrule,
		arg.HiddenOverrides,
		arg.RemovedRdates,
	)
	return err
}
