// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package storage

import (
	"context"
)

const countEventIdentitiesByCalendar = `-- name: CountEventIdentitiesByCalendar :one
SELECT COUNT(DISTINCT uid) FROM events WHERE calendar_id = ? AND uid != '' AND deleted_at IS NULL
`

// Distinct live event identities on a calendar. A recurring master and its
// overrides share a uid, so a series counts once - the number a
// "Moved N events" summary should report.
func (q *Queries) CountEventIdentitiesByCalendar(ctx context.Context, calendarID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventIdentitiesByCalendar, calendarID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countEventsByCalendar = `-- name: CountEventsByCalendar :one
SELECT COUNT(*) FROM events WHERE calendar_id = ? AND deleted_at IS NULL
`

func (q *Queries) CountEventsByCalendar(ctx context.Context, calendarID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEventsByCalendar, calendarID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createEvent = `-- name: CreateEvent :one
INSERT INTO events (
    uid, calendar_id, title, description, location,
    start_time, end_time, all_day, recurrence_rule,
    timezone, status, transp, sequence, priority,
    class, url, exdates, rdates, recurrence_id, geo, duration, dtstamp,
    conference_uri
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at
`

type CreateEventParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    *string
	Location       *string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule *string
	Timezone       *string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            *string
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Geo            *string
	Duration       *string
	Dtstamp        *string
	ConferenceUri  string
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, createEvent,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Sequence,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Duration,
		arg.Dtstamp,
		arg.ConferenceUri,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEvent = `-- name: GetEvent :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetEvent(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByCalendarUID = `-- name: GetEventByCalendarUID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE calendar_id = ? AND uid = ? AND recurrence_id = '' AND deleted_at IS NULL
`

type GetEventByCalendarUIDParams struct {
	CalendarID int64
	Uid        string
}

func (q *Queries) GetEventByCalendarUID(ctx context.Context, arg GetEventByCalendarUIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByCalendarUID, arg.CalendarID, arg.Uid)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByCalendarUIDAndRecurrenceID = `-- name: GetEventByCalendarUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE calendar_id = ? AND uid = ? AND recurrence_id = ? AND deleted_at IS NULL
`

type GetEventByCalendarUIDAndRecurrenceIDParams struct {
	CalendarID   int64
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetEventByCalendarUIDAndRecurrenceID(ctx context.Context, arg GetEventByCalendarUIDAndRecurrenceIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByCalendarUIDAndRecurrenceID, arg.CalendarID, arg.Uid, arg.RecurrenceID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByUID = `-- name: GetEventByUID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE uid = ? AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) GetEventByUID(ctx context.Context, uid string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUID, uid)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByUIDAndRecurrenceID = `-- name: GetEventByUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE uid = ? AND recurrence_id = ? AND deleted_at IS NULL
`

type GetEventByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetEventByUIDAndRecurrenceID(ctx context.Context, arg GetEventByUIDAndRecurrenceIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventByUIDIncludingDeleted = `-- name: GetEventByUIDIncludingDeleted :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE uid = ? AND recurrence_id = '' LIMIT 1
`

func (q *Queries) GetEventByUIDIncludingDeleted(ctx context.Context, uid string) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventByUIDIncludingDeleted, uid)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const getEventIncludingDeleted = `-- name: GetEventIncludingDeleted :one
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE id = ?
`

func (q *Queries) GetEventIncludingDeleted(ctx context.Context, id int64) (Event, error) {
	row := q.db.QueryRowContext(ctx, getEventIncludingDeleted, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const listDeletedEventsByCalendar = `-- name: ListDeletedEventsByCalendar :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events
WHERE calendar_id = ? AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedEventsByCalendar(ctx context.Context, calendarID int64) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedEventsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
			&i.ConferenceUri,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedOverrideRecurrenceIDs = `-- name: ListDeletedOverrideRecurrenceIDs :many
SELECT recurrence_id FROM events
WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NOT NULL
ORDER BY recurrence_id
`

func (q *Queries) ListDeletedOverrideRecurrenceIDs(ctx context.Context, uid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedOverrideRecurrenceIDs, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recurrence_id string
		if err := rows.Scan(&recurrence_id); err != nil {
			return nil, err
		}
		items = append(items, recurrence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByCalendarAndDateRange = `-- name: ListEventsByCalendarAndDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events
WHERE calendar_id = ? AND start_time < ? AND end_time > ? AND deleted_at IS NULL
ORDER BY start_time
`

type ListEventsByCalendarAndDateRangeParams struct {
	CalendarID int64
	StartTime  string
	EndTime    string
}

func (q *Queries) ListEventsByCalendarAndDateRange(ctx context.Context, arg ListEventsByCalendarAndDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByCalendarAndDateRange, arg.CalendarID, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
			&i.ConferenceUri,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventsByDateRange = `-- name: ListEventsByDateRange :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events
WHERE start_time < ? AND end_time > ? AND deleted_at IS NULL
ORDER BY start_time
`

type ListEventsByDateRangeParams struct {
	StartTime string
	EndTime   string
}

func (q *Queries) ListEventsByDateRange(ctx context.Context, arg ListEventsByDateRangeParams) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listEventsByDateRange, arg.StartTime, arg.EndTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
			&i.ConferenceUri,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLiveOverrideRecurrenceIDsAtOrAfter = `-- name: ListLiveOverrideRecurrenceIDsAtOrAfter :many
SELECT recurrence_id FROM events
WHERE uid = ? AND recurrence_id != '' AND recurrence_id >= ? AND deleted_at IS NULL
`

type ListLiveOverrideRecurrenceIDsAtOrAfterParams struct {
	Uid          string
	RecurrenceID string
}

// The recurrence_ids a truncation is about to hide: live overrides at/after
// the cutoff. Captured before SoftDeleteOverridesAtOrAfter so restore can
// re-show only these and not overrides deleted independently (issue #287).
func (q *Queries) ListLiveOverrideRecurrenceIDsAtOrAfter(ctx context.Context, arg ListLiveOverrideRecurrenceIDsAtOrAfterParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listLiveOverrideRecurrenceIDsAtOrAfter, arg.Uid, arg.RecurrenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recurrence_id string
		if err := rows.Scan(&recurrence_id); err != nil {
			return nil, err
		}
		items = append(items, recurrence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverridesByUID = `-- name: ListOverridesByUID :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events
WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NULL
ORDER BY recurrence_id
`

func (q *Queries) ListOverridesByUID(ctx context.Context, uid string) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listOverridesByUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
			&i.ConferenceUri,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringEvents = `-- name: ListRecurringEvents :many
SELECT id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at FROM events WHERE (recurrence_rule IS NOT NULL OR (rdates IS NOT NULL AND rdates != '')) AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) ListRecurringEvents(ctx context.Context) ([]Event, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringEvents)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Title,
			&i.Description,
			&i.Location,
			&i.StartTime,
			&i.EndTime,
			&i.AllDay,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Status,
			&i.Transp,
			&i.Sequence,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Duration,
			&i.Dtstamp,
			&i.ConferenceUri,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventIdentitiesDirtyForMigration = `-- name: MarkEventIdentitiesDirtyForMigration :exec
INSERT INTO sync_resources (calendar_id, uid, owner_type, dirty, sync_strategy)
SELECT ?, uid, 'event', 1, 'sync-token'
FROM events AS src
WHERE src.calendar_id = ? AND src.deleted_at IS NULL AND src.uid != ''
GROUP BY uid
ON CONFLICT(calendar_id, uid) DO UPDATE SET dirty = 1, rev = rev + 1
`

type MarkEventIdentitiesDirtyForMigrationParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// Flags every distinct live event identity on the source calendar dirty on
// the destination so the first sync after a migration uploads it. Runs before
// reassignment, while the source rows still identify exactly what moves, as
// one set-based statement instead of a per-UID loop. The destination is
// always account-linked (migration targets a discovered collection), so the
// account gate in MarkResourceDirty is not needed here.
func (q *Queries) MarkEventIdentitiesDirtyForMigration(ctx context.Context, arg MarkEventIdentitiesDirtyForMigrationParams) error {
	_, err := q.db.ExecContext(ctx, markEventIdentitiesDirtyForMigration, arg.CalendarID, arg.CalendarID_2)
	return err
}

const purgeEventByID = `-- name: PurgeEventByID :execrows
DELETE FROM events WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeEventByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeEventByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeSoftDeletedEvents = `-- name: PurgeSoftDeletedEvents :execrows
DELETE FROM events WHERE deleted_at IS NOT NULL AND deleted_at < ?
`

func (q *Queries) PurgeSoftDeletedEvents(ctx context.Context, deletedAt *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSoftDeletedEvents, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignEventsCalendar = `-- name: ReassignEventsCalendar :execrows
UPDATE events SET
    calendar_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE calendar_id = ?
`

type ReassignEventsCalendarParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// Bulk-move every event (live or soft-deleted) from one calendar to another.
// Used by calendar migration ("Move to Account"): the destination calendar is
// created/linked inside the same transaction before this runs, so the
// calendar_id FK always resolves. No deleted_at filter - soft-deleted rows
// move too so the trash view and purge keep working after migration.
func (q *Queries) ReassignEventsCalendar(ctx context.Context, arg ReassignEventsCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignEventsCalendar, arg.CalendarID, arg.CalendarID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreEvent = `-- name: RestoreEvent :exec
UPDATE events SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreEvent, id)
	return err
}

const restoreEventByUIDAndRecurrenceID = `-- name: RestoreEventByUIDAndRecurrenceID :exec
UPDATE events SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND recurrence_id = ? AND deleted_at IS NOT NULL
`

type RestoreEventByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) RestoreEventByUIDAndRecurrenceID(ctx context.Context, arg RestoreEventByUIDAndRecurrenceIDParams) error {
	_, err := q.db.ExecContext(ctx, restoreEventByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	return err
}

const restoreEventsByUID = `-- name: RestoreEventsByUID :execrows
UPDATE events SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreEventsByUID(ctx context.Context, uid string) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreEventsByUID, uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreOverridesAtOrAfter = `-- name: RestoreOverridesAtOrAfter :exec
UPDATE events SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND recurrence_id != '' AND recurrence_id >= ? AND deleted_at IS NOT NULL
`

type RestoreOverridesAtOrAfterParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) RestoreOverridesAtOrAfter(ctx context.Context, arg RestoreOverridesAtOrAfterParams) error {
	_, err := q.db.ExecContext(ctx, restoreOverridesAtOrAfter, arg.Uid, arg.RecurrenceID)
	return err
}

const softDeleteEvent = `-- name: SoftDeleteEvent :exec
UPDATE events SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEvent(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteEvent, id)
	return err
}

const softDeleteEventsByUID = `-- name: SoftDeleteEventsByUID :exec
UPDATE events SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteEventsByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, softDeleteEventsByUID, uid)
	return err
}

const softDeleteOverridesAtOrAfter = `-- name: SoftDeleteOverridesAtOrAfter :exec
UPDATE events SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND recurrence_id != '' AND recurrence_id >= ? AND deleted_at IS NULL
`

type SoftDeleteOverridesAtOrAfterParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) SoftDeleteOverridesAtOrAfter(ctx context.Context, arg SoftDeleteOverridesAtOrAfterParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteOverridesAtOrAfter, arg.Uid, arg.RecurrenceID)
	return err
}

const updateEvent = `-- name: UpdateEvent :one
UPDATE events SET
    title = ?, description = ?, location = ?,
    start_time = ?, end_time = ?, all_day = ?,
    recurrence_rule = ?, calendar_id = ?,
    timezone = ?, status = ?, transp = ?,
    sequence = sequence + 1, priority = ?,
    class = ?, url = ?,
    exdates = ?, rdates = ?, geo = ?,
    duration = ?, dtstamp = ?,
    conference_uri = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at
`

type UpdateEventParams struct {
	Title          string
	Description    *string
	Location       *string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule *string
	CalendarID     int64
	Timezone       *string
	Status         string
	Transp         string
	Priority       int64
	Class          string
	Url            *string
	Exdates        *string
	Rdates         *string
	Geo            *string
	Duration       *string
	Dtstamp        *string
	ConferenceUri  string
	ID             int64
}

func (q *Queries) UpdateEvent(ctx context.Context, arg UpdateEventParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, updateEvent,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.CalendarID,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.Geo,
		arg.Duration,
		arg.Dtstamp,
		arg.ConferenceUri,
		arg.ID,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}

const updateEventExdates = `-- name: UpdateEventExdates :exec
UPDATE events SET exdates = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateEventExdatesParams struct {
	Exdates *string
	ID      int64
}

func (q *Queries) UpdateEventExdates(ctx context.Context, arg UpdateEventExdatesParams) error {
	_, err := q.db.ExecContext(ctx, updateEventExdates, arg.Exdates, arg.ID)
	return err
}

const updateEventRdates = `-- name: UpdateEventRdates :exec
UPDATE events SET rdates = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateEventRdatesParams struct {
	Rdates *string
	ID     int64
}

func (q *Queries) UpdateEventRdates(ctx context.Context, arg UpdateEventRdatesParams) error {
	_, err := q.db.ExecContext(ctx, updateEventRdates, arg.Rdates, arg.ID)
	return err
}

const updateEventRecurrenceRule = `-- name: UpdateEventRecurrenceRule :exec
UPDATE events SET recurrence_rule = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateEventRecurrenceRuleParams struct {
	RecurrenceRule *string
	ID             int64
}

func (q *Queries) UpdateEventRecurrenceRule(ctx context.Context, arg UpdateEventRecurrenceRuleParams) error {
	_, err := q.db.ExecContext(ctx, updateEventRecurrenceRule, arg.RecurrenceRule, arg.ID)
	return err
}

const upsertEventByUID = `-- name: UpsertEventByUID :one
INSERT INTO events (
    uid, calendar_id, title, description, location,
    start_time, end_time, all_day, recurrence_rule,
    timezone, status, transp, sequence, priority,
    class, url, exdates, rdates, recurrence_id, geo, duration, dtstamp,
    conference_uri
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(calendar_id, uid, recurrence_id) DO UPDATE SET
    title = excluded.title, description = excluded.description,
    location = excluded.location, start_time = excluded.start_time,
    end_time = excluded.end_time, all_day = excluded.all_day,
    recurrence_rule = excluded.recurrence_rule,
    timezone = excluded.timezone, status = excluded.status,
    transp = excluded.transp,
    sequence = MAX(excluded.sequence, events.sequence + 1),
    priority = excluded.priority, class = excluded.class,
    url = excluded.url,
    exdates = excluded.exdates, rdates = excluded.rdates,
    geo = excluded.geo,
    duration = excluded.duration,
    dtstamp = excluded.dtstamp,
    conference_uri = excluded.conference_uri,
    deleted_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, title, description, location, start_time, end_time, all_day, recurrence_rule, timezone, status, transp, sequence, priority, class, url, exdates, rdates, recurrence_id, geo, created_at, updated_at, duration, dtstamp, conference_uri, deleted_at
`

type UpsertEventByUIDParams struct {
	Uid            string
	CalendarID     int64
	Title          string
	Description    *string
	Location       *string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule *string
	Timezone       *string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            *string
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Geo            *string
	Duration       *string
	Dtstamp        *string
	ConferenceUri  string
}

// NOTE: ON CONFLICT matches (calendar_id, uid, recurrence_id). The same
// UID on a second calendar inserts a new row (issue #756). ON CONFLICT
// UPDATE clears deleted_at. This query resurrects soft-deleted rows.
// Callers outside the pull path in the sync engine must know this. The
// pull path is safe. The engine excludes tombstoned UIDs before this
// query runs (engine.go loads tombstones first and skips them during pull).
func (q *Queries) UpsertEventByUID(ctx context.Context, arg UpsertEventByUIDParams) (Event, error) {
	row := q.db.QueryRowContext(ctx, upsertEventByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Title,
		arg.Description,
		arg.Location,
		arg.StartTime,
		arg.EndTime,
		arg.AllDay,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Status,
		arg.Transp,
		arg.Sequence,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Duration,
		arg.Dtstamp,
		arg.ConferenceUri,
	)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Title,
		&i.Description,
		&i.Location,
		&i.StartTime,
		&i.EndTime,
		&i.AllDay,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Status,
		&i.Transp,
		&i.Sequence,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Duration,
		&i.Dtstamp,
		&i.ConferenceUri,
		&i.DeletedAt,
	)
	return i, err
}
