// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: event_exdate_deletes.sql

package storage

import (
	"context"
)

const deleteEventExdateDelete = `-- name: DeleteEventExdateDelete :exec
DELETE FROM event_exdate_deletes WHERE id = ?
`

func (q *Queries) DeleteEventExdateDelete(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEventExdateDelete, id)
	return err
}

const deleteEventExdateDeleteChecked = `-- name: DeleteEventExdateDeleteChecked :execrows
DELETE FROM event_exdate_deletes WHERE id = ?
`

// Same delete as DeleteEventExdateDelete, but it reports the number of rows
// removed. A batch apply then fails when another operation consumed the log
// row between the batch check and the batch apply.
func (q *Queries) DeleteEventExdateDeleteChecked(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteEventExdateDeleteChecked, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEventExdateDelete = `-- name: GetEventExdateDelete :one
SELECT id, calendar_id, uid, recurrence_id, deleted_at FROM event_exdate_deletes WHERE id = ?
`

func (q *Queries) GetEventExdateDelete(ctx context.Context, id int64) (EventExdateDelete, error) {
	row := q.db.QueryRowContext(ctx, getEventExdateDelete, id)
	var i EventExdateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.RecurrenceID,
		&i.DeletedAt,
	)
	return i, err
}

const getEventExdateDeleteByUIDRecurrence = `-- name: GetEventExdateDeleteByUIDRecurrence :one
SELECT id, calendar_id, uid, recurrence_id, deleted_at FROM event_exdate_deletes WHERE uid = ? AND recurrence_id = ?
`

type GetEventExdateDeleteByUIDRecurrenceParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetEventExdateDeleteByUIDRecurrence(ctx context.Context, arg GetEventExdateDeleteByUIDRecurrenceParams) (EventExdateDelete, error) {
	row := q.db.QueryRowContext(ctx, getEventExdateDeleteByUIDRecurrence, arg.Uid, arg.RecurrenceID)
	var i EventExdateDelete
	err := row.Scan(
		&i.ID,
		&i.CalendarID,
		&i.Uid,
		&i.RecurrenceID,
		&i.DeletedAt,
	)
	return i, err
}

const listEventExdateDeletesByCalendar = `-- name: ListEventExdateDeletesByCalendar :many
SELECT id, calendar_id, uid, recurrence_id, deleted_at FROM event_exdate_deletes
WHERE calendar_id = ?
ORDER BY deleted_at DESC
`

func (q *Queries) ListEventExdateDeletesByCalendar(ctx context.Context, calendarID int64) ([]EventExdateDelete, error) {
	rows, err := q.db.QueryContext(ctx, listEventExdateDeletesByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EventExdateDelete
	for rows.Next() {
		var i EventExdateDelete
		if err := rows.Scan(
			&i.ID,
			&i.CalendarID,
			&i.Uid,
			&i.RecurrenceID,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeOldEventExdateDeletes = `-- name: PurgeOldEventExdateDeletes :execrows
DELETE FROM event_exdate_deletes WHERE deleted_at < ?
`

func (q *Queries) PurgeOldEventExdateDeletes(ctx context.Context, deletedAt string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeOldEventExdateDeletes, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const recordEventExdateDelete = `-- name: RecordEventExdateDelete :exec
INSERT INTO event_exdate_deletes (calendar_id, uid, recurrence_id)
VALUES (?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
`

type RecordEventExdateDeleteParams struct {
	CalendarID   int64
	Uid          string
	RecurrenceID string
}

// Idempotent: deleting the same instance twice leaves exactly one log row.
func (q *Queries) RecordEventExdateDelete(ctx context.Context, arg RecordEventExdateDeleteParams) error {
	_, err := q.db.ExecContext(ctx, recordEventExdateDelete, arg.CalendarID, arg.Uid, arg.RecurrenceID)
	return err
}
