// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: journals.sql

package storage

import (
	"context"
)

const countJournalIdentitiesByCalendar = `-- name: CountJournalIdentitiesByCalendar :one
SELECT COUNT(DISTINCT uid) FROM journals WHERE calendar_id = ? AND uid != '' AND deleted_at IS NULL
`

// See CountEventIdentitiesByCalendar.
func (q *Queries) CountJournalIdentitiesByCalendar(ctx context.Context, calendarID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countJournalIdentitiesByCalendar, calendarID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createJournal = `-- name: CreateJournal :one
INSERT INTO journals (
    uid, calendar_id, summary, description,
    start_date, status, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at
`

type CreateJournalParams struct {
	Uid            string
	CalendarID     int64
	Summary        string
	Description    *string
	StartDate      *string
	Status         string
	Class          string
	Url            *string
	RecurrenceRule *string
	Timezone       *string
	Sequence       int64
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Dtstamp        *string
}

func (q *Queries) CreateJournal(ctx context.Context, arg CreateJournalParams) (Journal, error) {
	row := q.db.QueryRowContext(ctx, createJournal,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.StartDate,
		arg.Status,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Dtstamp,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteJournal = `-- name: DeleteJournal :exec
DELETE FROM journals WHERE id = ?
`

func (q *Queries) DeleteJournal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteJournal, id)
	return err
}

const deleteJournalsByUID = `-- name: DeleteJournalsByUID :exec
DELETE FROM journals WHERE uid = ?
`

func (q *Queries) DeleteJournalsByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteJournalsByUID, uid)
	return err
}

const getJournal = `-- name: GetJournal :one
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetJournal(ctx context.Context, id int64) (Journal, error) {
	row := q.db.QueryRowContext(ctx, getJournal, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJournalByUID = `-- name: GetJournalByUID :one
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE uid = ? AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) GetJournalByUID(ctx context.Context, uid string) (Journal, error) {
	row := q.db.QueryRowContext(ctx, getJournalByUID, uid)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJournalByUIDAndRecurrenceID = `-- name: GetJournalByUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE uid = ? AND recurrence_id = ? AND deleted_at IS NULL
`

type GetJournalByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetJournalByUIDAndRecurrenceID(ctx context.Context, arg GetJournalByUIDAndRecurrenceIDParams) (Journal, error) {
	row := q.db.QueryRowContext(ctx, getJournalByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJournalByUIDIncludingDeleted = `-- name: GetJournalByUIDIncludingDeleted :one
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE uid = ? AND recurrence_id = ''
`

func (q *Queries) GetJournalByUIDIncludingDeleted(ctx context.Context, uid string) (Journal, error) {
	row := q.db.QueryRowContext(ctx, getJournalByUIDIncludingDeleted, uid)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getJournalIncludingDeleted = `-- name: GetJournalIncludingDeleted :one
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE id = ?
`

func (q *Queries) GetJournalIncludingDeleted(ctx context.Context, id int64) (Journal, error) {
	row := q.db.QueryRowContext(ctx, getJournalIncludingDeleted, id)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAllJournals = `-- name: ListAllJournals :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE deleted_at IS NULL ORDER BY start_date, summary
`

func (q *Queries) ListAllJournals(ctx context.Context) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listAllJournals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedJournalOverrideRecurrenceIDs = `-- name: ListDeletedJournalOverrideRecurrenceIDs :many
SELECT recurrence_id FROM journals
WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NOT NULL
ORDER BY recurrence_id
`

func (q *Queries) ListDeletedJournalOverrideRecurrenceIDs(ctx context.Context, uid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedJournalOverrideRecurrenceIDs, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recurrence_id string
		if err := rows.Scan(&recurrence_id); err != nil {
			return nil, err
		}
		items = append(items, recurrence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedJournalsByCalendar = `-- name: ListDeletedJournalsByCalendar :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals
WHERE calendar_id = ? AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedJournalsByCalendar(ctx context.Context, calendarID int64) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedJournalsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalOverridesByUID = `-- name: ListJournalOverridesByUID :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NULL ORDER BY recurrence_id
`

func (q *Queries) ListJournalOverridesByUID(ctx context.Context, uid string) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listJournalOverridesByUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournals = `-- name: ListJournals :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals
WHERE status != 'CANCELLED' AND deleted_at IS NULL
ORDER BY start_date, summary
`

func (q *Queries) ListJournals(ctx context.Context) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listJournals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByCalendar = `-- name: ListJournalsByCalendar :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals
WHERE calendar_id = ? AND status != 'CANCELLED' AND deleted_at IS NULL
ORDER BY start_date, summary
`

func (q *Queries) ListJournalsByCalendar(ctx context.Context, calendarID int64) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listJournalsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByStartDateRange = `-- name: ListJournalsByStartDateRange :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE start_date >= ? AND start_date < ? AND deleted_at IS NULL ORDER BY start_date, summary
`

type ListJournalsByStartDateRangeParams struct {
	StartDate   *string
	StartDate_2 *string
}

func (q *Queries) ListJournalsByStartDateRange(ctx context.Context, arg ListJournalsByStartDateRangeParams) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listJournalsByStartDateRange, arg.StartDate, arg.StartDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJournalsByStatus = `-- name: ListJournalsByStatus :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE status = ? AND deleted_at IS NULL ORDER BY start_date, summary
`

func (q *Queries) ListJournalsByStatus(ctx context.Context, status string) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listJournalsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringJournals = `-- name: ListRecurringJournals :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE (recurrence_rule IS NOT NULL OR (rdates IS NOT NULL AND rdates != '')) AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) ListRecurringJournals(ctx context.Context) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringJournals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringJournalsByCalendar = `-- name: ListRecurringJournalsByCalendar :many
SELECT id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at FROM journals WHERE recurrence_rule IS NOT NULL AND recurrence_id = '' AND calendar_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListRecurringJournalsByCalendar(ctx context.Context, calendarID int64) ([]Journal, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringJournalsByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Journal
	for rows.Next() {
		var i Journal
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.StartDate,
			&i.Status,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Dtstamp,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markJournalIdentitiesDirtyForMigration = `-- name: MarkJournalIdentitiesDirtyForMigration :exec
INSERT INTO sync_resources (calendar_id, uid, owner_type, dirty, sync_strategy)
SELECT ?, uid, 'journal', 1, 'sync-token'
FROM journals AS src
WHERE src.calendar_id = ? AND src.deleted_at IS NULL AND src.uid != ''
GROUP BY uid
ON CONFLICT(calendar_id, uid) DO UPDATE SET dirty = 1, rev = rev + 1
`

type MarkJournalIdentitiesDirtyForMigrationParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// See MarkEventIdentitiesDirtyForMigration.
func (q *Queries) MarkJournalIdentitiesDirtyForMigration(ctx context.Context, arg MarkJournalIdentitiesDirtyForMigrationParams) error {
	_, err := q.db.ExecContext(ctx, markJournalIdentitiesDirtyForMigration, arg.CalendarID, arg.CalendarID_2)
	return err
}

const purgeJournalByID = `-- name: PurgeJournalByID :execrows
DELETE FROM journals WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeJournalByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeJournalByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeSoftDeletedJournals = `-- name: PurgeSoftDeletedJournals :execrows
DELETE FROM journals WHERE deleted_at IS NOT NULL AND deleted_at < ?
`

func (q *Queries) PurgeSoftDeletedJournals(ctx context.Context, deletedAt *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSoftDeletedJournals, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignJournalsCalendar = `-- name: ReassignJournalsCalendar :execrows
UPDATE journals SET
    calendar_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE calendar_id = ?
`

type ReassignJournalsCalendarParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// Bulk-move every journal (live or soft-deleted) from one calendar to another
// during calendar migration. See ReassignEventsCalendar.
func (q *Queries) ReassignJournalsCalendar(ctx context.Context, arg ReassignJournalsCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignJournalsCalendar, arg.CalendarID, arg.CalendarID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreJournal = `-- name: RestoreJournal :exec
UPDATE journals SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreJournal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreJournal, id)
	return err
}

const restoreJournalRow = `-- name: RestoreJournalRow :execrows
UPDATE journals SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NOT NULL
`

// Same update as RestoreJournal, but it reports the number of rows changed.
// A batch apply then fails when another operation restored or purged the row
// between the batch check and the batch apply.
func (q *Queries) RestoreJournalRow(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreJournalRow, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreJournalsByUID = `-- name: RestoreJournalsByUID :execrows
UPDATE journals SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreJournalsByUID(ctx context.Context, uid string) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreJournalsByUID, uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteJournal = `-- name: SoftDeleteJournal :exec
UPDATE journals SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteJournal(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteJournal, id)
	return err
}

const softDeleteJournalsByUID = `-- name: SoftDeleteJournalsByUID :exec
UPDATE journals SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteJournalsByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, softDeleteJournalsByUID, uid)
	return err
}

const updateJournal = `-- name: UpdateJournal :one
UPDATE journals SET
    summary = ?, description = ?,
    start_date = ?,
    status = ?, calendar_id = ?,
    class = ?, url = ?,
    recurrence_rule = ?, timezone = ?,
    sequence = sequence + 1,
    exdates = ?, rdates = ?,
    dtstamp = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at
`

type UpdateJournalParams struct {
	Summary        string
	Description    *string
	StartDate      *string
	Status         string
	CalendarID     int64
	Class          string
	Url            *string
	RecurrenceRule *string
	Timezone       *string
	Exdates        *string
	Rdates         *string
	Dtstamp        *string
	ID             int64
}

func (q *Queries) UpdateJournal(ctx context.Context, arg UpdateJournalParams) (Journal, error) {
	row := q.db.QueryRowContext(ctx, updateJournal,
		arg.Summary,
		arg.Description,
		arg.StartDate,
		arg.Status,
		arg.CalendarID,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Exdates,
		arg.Rdates,
		arg.Dtstamp,
		arg.ID,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateJournalExdates = `-- name: UpdateJournalExdates :exec
UPDATE journals SET exdates = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateJournalExdatesParams struct {
	Exdates *string
	ID      int64
}

func (q *Queries) UpdateJournalExdates(ctx context.Context, arg UpdateJournalExdatesParams) error {
	_, err := q.db.ExecContext(ctx, updateJournalExdates, arg.Exdates, arg.ID)
	return err
}

const upsertJournalByUID = `-- name: UpsertJournalByUID :one
INSERT INTO journals (
    uid, calendar_id, summary, description,
    start_date, status, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    calendar_id = excluded.calendar_id,
    summary = excluded.summary, description = excluded.description,
    start_date = excluded.start_date,
    status = excluded.status,
    class = excluded.class, url = excluded.url,
    recurrence_rule = excluded.recurrence_rule,
    timezone = excluded.timezone,
    sequence = MAX(excluded.sequence, journals.sequence + 1),
    exdates = excluded.exdates, rdates = excluded.rdates,
    dtstamp = excluded.dtstamp,
    deleted_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, summary, description, start_date, status, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, dtstamp, created_at, updated_at, deleted_at
`

type UpsertJournalByUIDParams struct {
	Uid            string
	CalendarID     int64
	Summary        string
	Description    *string
	StartDate      *string
	Status         string
	Class          string
	Url            *string
	RecurrenceRule *string
	Timezone       *string
	Sequence       int64
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Dtstamp        *string
}

// NOTE: ON CONFLICT UPDATE clears deleted_at. This query resurrects
// soft-deleted rows. Callers outside the pull path in the sync engine
// must know this. The pull path is safe. The engine excludes
// tombstoned UIDs before this query runs (engine.go loads tombstones
// first and skips them during pull).
func (q *Queries) UpsertJournalByUID(ctx context.Context, arg UpsertJournalByUIDParams) (Journal, error) {
	row := q.db.QueryRowContext(ctx, upsertJournalByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.StartDate,
		arg.Status,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Dtstamp,
	)
	var i Journal
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.StartDate,
		&i.Status,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Dtstamp,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
