// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package storage

type Account struct {
	ID           int64
	Name         string
	ServerUrl    string
	AuthType     string
	Username     string
	CreatedAt    string
	UpdatedAt    string
	DisplayOrder int64
}

type AlarmState struct {
	ID             int64
	AlarmID        int64
	EventID        int64
	TriggerAt      string
	FiredAt        *string
	AckedAt        *string
	SnoozedTo      *string
	DispatchStatus string
	ClaimedAt      *string
	ClaimToken     *string
	Attempts       int64
	RetryAt        *string
	LastError      *string
	DeliveredAt    *string
}

type Calendar struct {
	ID                  int64
	Name                string
	Color               string
	Description         *string
	CreatedAt           string
	UpdatedAt           string
	AccountID           *int64
	RemoteUrl           *string
	Ctag                *string
	SyncToken           *string
	LastSyncAt          *string
	LastSyncAttemptedAt *string
	LastSyncError       *string
	RemoteColor         *string
	ColorDirty          int64
	OwnerEmail          string
	IsDefault           int64
	DisplayOrder        int64
	RemoteName          string
	RemoteAccess        string
	RemoteComponents    string
	RemoteMissing       int64
}

type CredentialLocation struct {
	Location     string
	MaxAccountID int64
}

type CredentialNamespace struct {
	ID              int64
	Namespace       string
	CurrentLocation string
}

type Event struct {
	ID             int64
	Uid            string
	CalendarID     int64
	Title          string
	Description    *string
	Location       *string
	StartTime      string
	EndTime        string
	AllDay         int64
	RecurrenceRule *string
	Timezone       *string
	Status         string
	Transp         string
	Sequence       int64
	Priority       int64
	Class          string
	Url            *string
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Geo            *string
	CreatedAt      string
	UpdatedAt      string
	Duration       *string
	Dtstamp        *string
	ConferenceUri  string
	DeletedAt      *string
}

type EventAlarm struct {
	ID            int64
	EventID       int64
	Action        string
	TriggerValue  string
	Description   *string
	Repeat        int64
	Duration      *string
	Related       string
	Summary       *string
	Uid           *string
	Acknowledged  *string
	AttachUri     *string
	AttachFmttype *string
	AttachBinary  []byte
}

type EventAlarmAttendee struct {
	ID      int64
	AlarmID int64
	Email   string
	Name    *string
}

type EventAttachment struct {
	ID       int64
	EventID  int64
	Uri      *string
	Fmttype  *string
	Data     []byte
	Filename *string
}

type EventAttendee struct {
	ID            int64
	EventID       int64
	Email         string
	Name          *string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        *string
	Rsvp          *string
	SentBy        *string
	DelegatedTo   *string
	DelegatedFrom *string
	Member        *string
	Dir           *string
	Language      *string
}

type EventCategory struct {
	EventID  int64
	Category string
	Position int64
}

type EventComment struct {
	ID      int64
	EventID int64
	Text    string
}

type EventContact struct {
	ID      int64
	EventID int64
	Text    string
}

type EventExdateDelete struct {
	ID           int64
	CalendarID   int64
	Uid          string
	RecurrenceID string
	DeletedAt    string
}

type EventRelation struct {
	ID      int64
	EventID int64
	RelType string
	RelUid  string
}

type EventResource struct {
	ID      int64
	EventID int64
	Text    string
}

type EventTruncateDelete struct {
	ID              int64
	CalendarID      int64
	Uid             string
	CutoffTime      string
	PreviousRrule   string
	DeletedAt       string
	HiddenOverrides *string
	RemovedRdates   *string
}

type EventsFt struct {
	Title       string
	Description string
	Location    string
	Categories  string
}

type Journal struct {
	ID             int64
	Uid            string
	CalendarID     int64
	Summary        string
	Description    *string
	StartDate      *string
	Status         string
	Class          string
	Url            *string
	RecurrenceRule *string
	Timezone       *string
	Sequence       int64
	Exdates        *string
	Rdates         *string
	RecurrenceID   string
	Dtstamp        *string
	CreatedAt      string
	UpdatedAt      string
	DeletedAt      *string
}

type JournalAttachment struct {
	ID        int64
	JournalID int64
	Uri       *string
	Fmttype   *string
	Data      []byte
	Filename  *string
}

type JournalAttendee struct {
	ID            int64
	JournalID     int64
	Email         string
	Name          *string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        *string
	Rsvp          *string
	SentBy        *string
	DelegatedTo   *string
	DelegatedFrom *string
	Member        *string
	Dir           *string
	Language      *string
}

type JournalCategory struct {
	JournalID int64
	Category  string
	Position  int64
}

type JournalComment struct {
	ID        int64
	JournalID int64
	Text      string
}

type JournalContact struct {
	ID        int64
	JournalID int64
	Text      string
}

type JournalExdateDelete struct {
	ID           int64
	CalendarID   int64
	Uid          string
	RecurrenceID string
	DeletedAt    string
}

type JournalRelation struct {
	ID        int64
	JournalID int64
	RelType   string
	RelUid    string
}

type JournalsFt struct {
	Summary     string
	Description string
	Categories  string
}

type SyncConflict struct {
	ID         int64
	CalendarID int64
	OwnerType  string
	OwnerID    int64
	Uid        string
	LocalIcal  string
	ServerIcal string
	ServerEtag string
	DetectedAt string
	ResolvedAt *string
	Resolution *string
}

type SyncPendingHref struct {
	ID         int64
	CalendarID int64
	Href       string
	MissCount  int64
}

type SyncResource struct {
	ID            int64
	CalendarID    int64
	Uid           string
	OwnerType     string
	RemoteUrl     string
	Etag          string
	Dirty         int64
	SyncStrategy  string
	Rev           int64
	PushFailCount int64
	LastPushError string
}

type Timezone struct {
	Tzid          string
	VtimezoneData string
	CreatedAt     string
	Source        string
}

type Todo struct {
	ID              int64
	Uid             string
	CalendarID      int64
	Summary         string
	Description     *string
	Location        *string
	DueDate         *string
	StartDate       *string
	Duration        *string
	CompletedAt     *string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             *string
	RecurrenceRule  *string
	Timezone        *string
	Sequence        int64
	Exdates         *string
	Rdates          *string
	RecurrenceID    string
	Geo             *string
	CreatedAt       string
	UpdatedAt       string
	Dtstamp         *string
	DeletedAt       *string
}

type TodoAlarm struct {
	ID            int64
	TodoID        int64
	Action        string
	TriggerValue  string
	Description   *string
	Repeat        int64
	Duration      *string
	Related       string
	Summary       *string
	Uid           *string
	Acknowledged  *string
	AttachUri     *string
	AttachFmttype *string
	AttachBinary  []byte
}

type TodoAlarmAttendee struct {
	ID      int64
	AlarmID int64
	Email   string
	Name    *string
}

type TodoAlarmState struct {
	ID             int64
	AlarmID        int64
	TodoID         int64
	TriggerAt      string
	FiredAt        *string
	AckedAt        *string
	SnoozedTo      *string
	DispatchStatus string
	ClaimedAt      *string
	ClaimToken     *string
	Attempts       int64
	RetryAt        *string
	LastError      *string
	DeliveredAt    *string
}

type TodoAttachment struct {
	ID       int64
	TodoID   int64
	Uri      *string
	Fmttype  *string
	Data     []byte
	Filename *string
}

type TodoAttendee struct {
	ID            int64
	TodoID        int64
	Email         string
	Name          *string
	RsvpStatus    string
	Role          string
	Organizer     int64
	Cutype        *string
	Rsvp          *string
	SentBy        *string
	DelegatedTo   *string
	DelegatedFrom *string
	Member        *string
	Dir           *string
	Language      *string
}

type TodoCategory struct {
	TodoID   int64
	Category string
	Position int64
}

type TodoComment struct {
	ID     int64
	TodoID int64
	Text   string
}

type TodoContact struct {
	ID     int64
	TodoID int64
	Text   string
}

type TodoExdateDelete struct {
	ID           int64
	CalendarID   int64
	Uid          string
	RecurrenceID string
	DeletedAt    string
}

type TodoRelation struct {
	ID      int64
	TodoID  int64
	RelType string
	RelUid  string
}

type TodoResource struct {
	ID     int64
	TodoID int64
	Text   string
}

type TodosFt struct {
	Summary     string
	Description string
	Location    string
	Categories  string
}

type Tombstone struct {
	ID         int64
	CalendarID int64
	Uid        string
	RemoteUrl  string
	DeletedAt  string
}

type XProperty struct {
	ID        int64
	OwnerType string
	OwnerID   int64
	Name      string
	Value     string
	Params    string
}
