// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: todos.sql

package storage

import (
	"context"
)

const completeTodo = `-- name: CompleteTodo :one
UPDATE todos SET
    status = 'COMPLETED',
    completed_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    percent_complete = 100,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at
`

func (q *Queries) CompleteTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, completeTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const countTodoIdentitiesByCalendar = `-- name: CountTodoIdentitiesByCalendar :one
SELECT COUNT(DISTINCT uid) FROM todos WHERE calendar_id = ? AND uid != '' AND deleted_at IS NULL
`

// See CountEventIdentitiesByCalendar.
func (q *Queries) CountTodoIdentitiesByCalendar(ctx context.Context, calendarID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTodoIdentitiesByCalendar, calendarID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (
    uid, calendar_id, summary, description, location,
    due_date, start_date, duration, completed_at, percent_complete,
    status, priority, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at
`

type CreateTodoParams struct {
	Uid             string
	CalendarID      int64
	Summary         string
	Description     *string
	Location        *string
	DueDate         *string
	StartDate       *string
	Duration        *string
	CompletedAt     *string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             *string
	RecurrenceRule  *string
	Timezone        *string
	Sequence        int64
	Exdates         *string
	Rdates          *string
	RecurrenceID    string
	Geo             *string
	Dtstamp         *string
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Dtstamp,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = ?
`

func (q *Queries) DeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

const deleteTodosByUID = `-- name: DeleteTodosByUID :exec
DELETE FROM todos WHERE uid = ?
`

func (q *Queries) DeleteTodosByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, deleteTodosByUID, uid)
	return err
}

const getTodo = `-- name: GetTodo :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) GetTodo(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const getTodoByUID = `-- name: GetTodoByUID :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE uid = ? AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) GetTodoByUID(ctx context.Context, uid string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByUID, uid)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const getTodoByUIDAndRecurrenceID = `-- name: GetTodoByUIDAndRecurrenceID :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE uid = ? AND recurrence_id = ? AND deleted_at IS NULL
`

type GetTodoByUIDAndRecurrenceIDParams struct {
	Uid          string
	RecurrenceID string
}

func (q *Queries) GetTodoByUIDAndRecurrenceID(ctx context.Context, arg GetTodoByUIDAndRecurrenceIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByUIDAndRecurrenceID, arg.Uid, arg.RecurrenceID)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const getTodoByUIDIncludingDeleted = `-- name: GetTodoByUIDIncludingDeleted :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE uid = ? AND recurrence_id = ''
`

func (q *Queries) GetTodoByUIDIncludingDeleted(ctx context.Context, uid string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoByUIDIncludingDeleted, uid)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const getTodoIncludingDeleted = `-- name: GetTodoIncludingDeleted :one
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE id = ?
`

func (q *Queries) GetTodoIncludingDeleted(ctx context.Context, id int64) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodoIncludingDeleted, id)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const listAllTodos = `-- name: ListAllTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE deleted_at IS NULL ORDER BY due_date, summary
`

func (q *Queries) ListAllTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listAllTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTodoOverrideRecurrenceIDs = `-- name: ListDeletedTodoOverrideRecurrenceIDs :many
SELECT recurrence_id FROM todos
WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NOT NULL
ORDER BY recurrence_id
`

func (q *Queries) ListDeletedTodoOverrideRecurrenceIDs(ctx context.Context, uid string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedTodoOverrideRecurrenceIDs, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var recurrence_id string
		if err := rows.Scan(&recurrence_id); err != nil {
			return nil, err
		}
		items = append(items, recurrence_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedTodosByCalendar = `-- name: ListDeletedTodosByCalendar :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos
WHERE calendar_id = ? AND deleted_at IS NOT NULL
ORDER BY deleted_at DESC
`

func (q *Queries) ListDeletedTodosByCalendar(ctx context.Context, calendarID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedTodosByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTodos = `-- name: ListRecurringTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE (recurrence_rule IS NOT NULL OR (rdates IS NOT NULL AND rdates != '')) AND recurrence_id = '' AND deleted_at IS NULL
`

func (q *Queries) ListRecurringTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringTodosByCalendar = `-- name: ListRecurringTodosByCalendar :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE recurrence_rule IS NOT NULL AND recurrence_id = '' AND calendar_id = ? AND deleted_at IS NULL
`

func (q *Queries) ListRecurringTodosByCalendar(ctx context.Context, calendarID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listRecurringTodosByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodoOverridesByUID = `-- name: ListTodoOverridesByUID :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE uid = ? AND recurrence_id != '' AND deleted_at IS NULL ORDER BY recurrence_id
`

func (q *Queries) ListTodoOverridesByUID(ctx context.Context, uid string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodoOverridesByUID, uid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodos = `-- name: ListTodos :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos
WHERE status != 'COMPLETED' AND status != 'CANCELLED' AND deleted_at IS NULL
ORDER BY due_date, summary
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByCalendar = `-- name: ListTodosByCalendar :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos
WHERE calendar_id = ? AND status != 'COMPLETED' AND status != 'CANCELLED' AND deleted_at IS NULL
ORDER BY due_date, summary
`

func (q *Queries) ListTodosByCalendar(ctx context.Context, calendarID int64) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByCalendar, calendarID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByDueDateRange = `-- name: ListTodosByDueDateRange :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE due_date >= ? AND due_date < ? AND deleted_at IS NULL ORDER BY due_date, summary
`

type ListTodosByDueDateRangeParams struct {
	DueDate   *string
	DueDate_2 *string
}

func (q *Queries) ListTodosByDueDateRange(ctx context.Context, arg ListTodosByDueDateRangeParams) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByDueDateRange, arg.DueDate, arg.DueDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTodosByStatus = `-- name: ListTodosByStatus :many
SELECT id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at FROM todos WHERE status = ? AND deleted_at IS NULL ORDER BY due_date, summary
`

func (q *Queries) ListTodosByStatus(ctx context.Context, status string) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodosByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.Uid,
			&i.CalendarID,
			&i.Summary,
			&i.Description,
			&i.Location,
			&i.DueDate,
			&i.StartDate,
			&i.Duration,
			&i.CompletedAt,
			&i.PercentComplete,
			&i.Status,
			&i.Priority,
			&i.Class,
			&i.Url,
			&i.RecurrenceRule,
			&i.Timezone,
			&i.Sequence,
			&i.Exdates,
			&i.Rdates,
			&i.RecurrenceID,
			&i.Geo,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Dtstamp,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTodoIdentitiesDirtyForMigration = `-- name: MarkTodoIdentitiesDirtyForMigration :exec
INSERT INTO sync_resources (calendar_id, uid, owner_type, dirty, sync_strategy)
SELECT ?, uid, 'todo', 1, 'sync-token'
FROM todos AS src
WHERE src.calendar_id = ? AND src.deleted_at IS NULL AND src.uid != ''
GROUP BY uid
ON CONFLICT(calendar_id, uid) DO UPDATE SET dirty = 1, rev = rev + 1
`

type MarkTodoIdentitiesDirtyForMigrationParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// See MarkEventIdentitiesDirtyForMigration.
func (q *Queries) MarkTodoIdentitiesDirtyForMigration(ctx context.Context, arg MarkTodoIdentitiesDirtyForMigrationParams) error {
	_, err := q.db.ExecContext(ctx, markTodoIdentitiesDirtyForMigration, arg.CalendarID, arg.CalendarID_2)
	return err
}

const moveTodosToCalendar = `-- name: MoveTodosToCalendar :execrows
UPDATE todos SET
    calendar_id = ?1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ?2 AND calendar_id = ?3
`

type MoveTodosToCalendarParams struct {
	DestinationCalendarID int64
	Uid                   string
	SourceCalendarID      int64
}

// Move every todo row of one UID (master and overrides, live and
// soft-deleted) from one calendar to another. A cross-calendar move must
// move the master and its overrides together: CalDAV tracks one resource
// per UID, and expansion keys overrides on (calendar_id, uid).
// Soft-deleted rows move too, so trash and purge keep working. Child
// collections key on the row id. They follow without a rewrite.
func (q *Queries) MoveTodosToCalendar(ctx context.Context, arg MoveTodosToCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, moveTodosToCalendar, arg.DestinationCalendarID, arg.Uid, arg.SourceCalendarID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeSoftDeletedTodos = `-- name: PurgeSoftDeletedTodos :execrows
DELETE FROM todos WHERE deleted_at IS NOT NULL AND deleted_at < ?
`

func (q *Queries) PurgeSoftDeletedTodos(ctx context.Context, deletedAt *string) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeSoftDeletedTodos, deletedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const purgeTodoByID = `-- name: PurgeTodoByID :execrows
DELETE FROM todos WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) PurgeTodoByID(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, purgeTodoByID, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const reassignTodosCalendar = `-- name: ReassignTodosCalendar :execrows
UPDATE todos SET
    calendar_id = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE calendar_id = ?
`

type ReassignTodosCalendarParams struct {
	CalendarID   int64
	CalendarID_2 int64
}

// Bulk-move every todo (live or soft-deleted) from one calendar to another
// during calendar migration. See ReassignEventsCalendar.
func (q *Queries) ReassignTodosCalendar(ctx context.Context, arg ReassignTodosCalendarParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, reassignTodosCalendar, arg.CalendarID, arg.CalendarID_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const restoreTodo = `-- name: RestoreTodo :exec
UPDATE todos SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, restoreTodo, id)
	return err
}

const restoreTodosByUID = `-- name: RestoreTodosByUID :execrows
UPDATE todos SET
    deleted_at = NULL,
    sequence = sequence + 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NOT NULL
`

func (q *Queries) RestoreTodosByUID(ctx context.Context, uid string) (int64, error) {
	result, err := q.db.ExecContext(ctx, restoreTodosByUID, uid)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const softDeleteTodo = `-- name: SoftDeleteTodo :exec
UPDATE todos SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodo(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodo, id)
	return err
}

const softDeleteTodosByCalendarAndUID = `-- name: SoftDeleteTodosByCalendarAndUID :exec
UPDATE todos SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE calendar_id = ? AND uid = ? AND deleted_at IS NULL
`

type SoftDeleteTodosByCalendarAndUIDParams struct {
	CalendarID int64
	Uid        string
}

// Calendar-scoped counterpart of SoftDeleteTodosByUID. Pull-driven
// deletions use this form so a server-reported deletion on one calendar
// cannot soft-delete rows with the same UID on another calendar. Those
// rows are an issue #756 copy or a resource moved cross-calendar.
func (q *Queries) SoftDeleteTodosByCalendarAndUID(ctx context.Context, arg SoftDeleteTodosByCalendarAndUIDParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodosByCalendarAndUID, arg.CalendarID, arg.Uid)
	return err
}

const softDeleteTodosByUID = `-- name: SoftDeleteTodosByUID :exec
UPDATE todos SET
    deleted_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now'),
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE uid = ? AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTodosByUID(ctx context.Context, uid string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTodosByUID, uid)
	return err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET
    summary = ?, description = ?, location = ?,
    due_date = ?, start_date = ?, duration = ?,
    completed_at = ?, percent_complete = ?,
    status = ?, calendar_id = ?, priority = ?,
    class = ?, url = ?,
    recurrence_rule = ?, timezone = ?,
    sequence = sequence + 1,
    exdates = ?, rdates = ?, geo = ?,
    dtstamp = ?,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
WHERE id = ? RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at
`

type UpdateTodoParams struct {
	Summary         string
	Description     *string
	Location        *string
	DueDate         *string
	StartDate       *string
	Duration        *string
	CompletedAt     *string
	PercentComplete int64
	Status          string
	CalendarID      int64
	Priority        int64
	Class           string
	Url             *string
	RecurrenceRule  *string
	Timezone        *string
	Exdates         *string
	Rdates          *string
	Geo             *string
	Dtstamp         *string
	ID              int64
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.CalendarID,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Exdates,
		arg.Rdates,
		arg.Geo,
		arg.Dtstamp,
		arg.ID,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}

const updateTodoExdates = `-- name: UpdateTodoExdates :exec
UPDATE todos SET exdates = ?, updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now') WHERE id = ?
`

type UpdateTodoExdatesParams struct {
	Exdates *string
	ID      int64
}

func (q *Queries) UpdateTodoExdates(ctx context.Context, arg UpdateTodoExdatesParams) error {
	_, err := q.db.ExecContext(ctx, updateTodoExdates, arg.Exdates, arg.ID)
	return err
}

const upsertTodoByUID = `-- name: UpsertTodoByUID :one
INSERT INTO todos (
    uid, calendar_id, summary, description, location,
    due_date, start_date, duration, completed_at, percent_complete,
    status, priority, class, url,
    recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, dtstamp
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(uid, recurrence_id) DO UPDATE SET
    calendar_id = excluded.calendar_id,
    summary = excluded.summary, description = excluded.description,
    location = excluded.location, due_date = excluded.due_date,
    start_date = excluded.start_date, duration = excluded.duration,
    completed_at = excluded.completed_at, percent_complete = excluded.percent_complete,
    status = excluded.status, priority = excluded.priority,
    class = excluded.class, url = excluded.url,
    recurrence_rule = excluded.recurrence_rule,
    timezone = excluded.timezone,
    sequence = MAX(excluded.sequence, todos.sequence + 1),
    exdates = excluded.exdates, rdates = excluded.rdates,
    geo = excluded.geo,
    dtstamp = excluded.dtstamp,
    deleted_at = NULL,
    updated_at = strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
RETURNING id, uid, calendar_id, summary, description, location, due_date, start_date, duration, completed_at, percent_complete, status, priority, class, url, recurrence_rule, timezone, sequence, exdates, rdates, recurrence_id, geo, created_at, updated_at, dtstamp, deleted_at
`

type UpsertTodoByUIDParams struct {
	Uid             string
	CalendarID      int64
	Summary         string
	Description     *string
	Location        *string
	DueDate         *string
	StartDate       *string
	Duration        *string
	CompletedAt     *string
	PercentComplete int64
	Status          string
	Priority        int64
	Class           string
	Url             *string
	RecurrenceRule  *string
	Timezone        *string
	Sequence        int64
	Exdates         *string
	Rdates          *string
	RecurrenceID    string
	Geo             *string
	Dtstamp         *string
}

// NOTE: ON CONFLICT UPDATE clears deleted_at. This query resurrects
// soft-deleted rows. Callers outside the pull path in the sync engine
// must know this. The pull path is safe. The engine excludes
// tombstoned UIDs before this query runs (engine.go loads tombstones
// first and skips them during pull).
func (q *Queries) UpsertTodoByUID(ctx context.Context, arg UpsertTodoByUIDParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, upsertTodoByUID,
		arg.Uid,
		arg.CalendarID,
		arg.Summary,
		arg.Description,
		arg.Location,
		arg.DueDate,
		arg.StartDate,
		arg.Duration,
		arg.CompletedAt,
		arg.PercentComplete,
		arg.Status,
		arg.Priority,
		arg.Class,
		arg.Url,
		arg.RecurrenceRule,
		arg.Timezone,
		arg.Sequence,
		arg.Exdates,
		arg.Rdates,
		arg.RecurrenceID,
		arg.Geo,
		arg.Dtstamp,
	)
	var i Todo
	err := row.Scan(
		&i.ID,
		&i.Uid,
		&i.CalendarID,
		&i.Summary,
		&i.Description,
		&i.Location,
		&i.DueDate,
		&i.StartDate,
		&i.Duration,
		&i.CompletedAt,
		&i.PercentComplete,
		&i.Status,
		&i.Priority,
		&i.Class,
		&i.Url,
		&i.RecurrenceRule,
		&i.Timezone,
		&i.Sequence,
		&i.Exdates,
		&i.Rdates,
		&i.RecurrenceID,
		&i.Geo,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Dtstamp,
		&i.DeletedAt,
	)
	return i, err
}
